### ISSUE TITLE
Expand on filters to allow for more options when configuring the filter

### ISSUE THREAD

**Issue by Hyphen8** [HYPHENATE/HelpMessages#9]
Expand on the SOQL support to include

GREATER THAN >
LESS THAN <
GREATER THAN OR EQUAL >=
LESS THAN OR EQUAL <=

This need investigation as this might be pending the setup of different comparison data types.

**Comment by danielbprobert** [comment]
expanded on support to include these operators will work with percent and decimal and percent values
